languageCode = "en-us"
title = 'yo_soy_rafa'
theme="archie"

# Code Highlight
pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=3 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Hola, soy rafa y este es mi blog para tomar notas y compartir las cosas que me generan alguna dosis de fascinación."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customcss = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"


# Main menu Items
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4